services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0

  model-training:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: model-training
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../reports:/app/reports
      - ../src:/app/src
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  
    # command: bash src/train.py
    stdin_open: true
    tty: true
