services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0

  model-training:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: model-training
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../reports:/app/reports
      - ../src:/app/src
      - ../artifacts:/app/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  
    stdin_open: true
    tty: true

  carbon-api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: carbon-api
    volumes:
      - ../backend:/app
    ports:
      - "8000:5050"
    restart: always
    stdin_open: true
    tty: true

  carbon-ui:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: carbon-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always


    
